name: pydynsm_dev_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - loguru
  # IDE / notebooks
  - spyder
  - ipykernel
  # PIP stuff
  - pip 
  # dev related
  # packaging / build 
  - setuptools>=69
  - wheel
  - build
  # testing 
  - pytest
  # documentation
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  - mkdocstrings-python
        
